// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7mp0HE9pDX0Otb66NgF3xaq8tvFqJjMY',
    appId: '1:103765634654:web:1c208459f4221bf516cecf',
    messagingSenderId: '103765634654',
    projectId: 'shop-f8b65',
    authDomain: 'shop-f8b65.firebaseapp.com',
    storageBucket: 'shop-f8b65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_lEO3KWAh4lqNbMZ9HrHup0pwKGHJMqw',
    appId: '1:103765634654:android:7ec973b6666f09d016cecf',
    messagingSenderId: '103765634654',
    projectId: 'shop-f8b65',
    storageBucket: 'shop-f8b65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeCS-cV-tvMXuJcOJzVRQYbcgHDzOppbw',
    appId: '1:103765634654:ios:1f0bb527228f541d16cecf',
    messagingSenderId: '103765634654',
    projectId: 'shop-f8b65',
    storageBucket: 'shop-f8b65.firebasestorage.app',
    iosBundleId: 'com.example.newshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeCS-cV-tvMXuJcOJzVRQYbcgHDzOppbw',
    appId: '1:103765634654:ios:1f0bb527228f541d16cecf',
    messagingSenderId: '103765634654',
    projectId: 'shop-f8b65',
    storageBucket: 'shop-f8b65.firebasestorage.app',
    iosBundleId: 'com.example.newshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7mp0HE9pDX0Otb66NgF3xaq8tvFqJjMY',
    appId: '1:103765634654:web:f0e51f4409a4bef516cecf',
    messagingSenderId: '103765634654',
    projectId: 'shop-f8b65',
    authDomain: 'shop-f8b65.firebaseapp.com',
    storageBucket: 'shop-f8b65.firebasestorage.app',
  );
}
